#!/bin/tcsh

set file = $1
set EQ_SAC_DIR = $2
if($file == "" || $EQ_SAC_DIR == "") then
echo "non input file find !"
exit 0
endif


##set DATADIR = /mnt/soddisk/soduser/Merge.Mw6.50km
set DATADIR = $2

##csh ~/bin/get_EQ_sac $file

cp -r $DATADIR/$file .

