#!/bin/tcsh


set PWD = `pwd`
mkdir -p ../PLOTDIR
mkdir -p ../DATADIR
mkdir -p ../TIMEDIR
cd ..
/bin/rm -rf Maligaro > & /dev/null
git clone https://github.com/Leviyu/Maligaro.git


set DIR = `pwd`
cd $PWD
sed -i '/BIGDIR/c\<BIGDIR>				'$DIR'' $PWD/INFILE.mother


