#!/bin/tcsh


set PWD = `pwd`
mkdir -p ../PLOTDIR
mkdir -p ../DATADIR
mkdir -p ../TIMEDIR
cd ..
/bin/rm -r Maligaro > & /dev/null
git clone https://github.com/Leviyu/Maligaro.git


cd ..
set DIR = `pwd`
cd -
sed -i '/BIGDIR/c\<BIGDIR>				'$DIR'' $PWD/INFILE.mother


