#!/bin/tcsh


set PWD = `pwd`
mkdir -p ../PLOTDIR
mkdir -p ../DATADIR
mkdir -p ../TIMEDIR
cd ..
/bin/rm -rf Maligaro > & /dev/null
git clone https://github.com/Leviyu/Maligaro.git


set DIR = `pwd`
cd $PWD
sed -i '/BIGDIR/c\<BIGDIR>				'$DIR'' $PWD/INFILE.mother



# set up environment variable
set INFILE = $PWD/INFILE.mother
set GMT_DIR = `cat $INFILE|grep GMT_DIR |awk '{print $2}'`
set TAUP_DIR = `cat $INFILE|grep TAUPDIR |awk '{print $2}'`
echo "set path=($path ${GMT_DIR})" >> ~/.tcshrc
echo "set path=($path ${TAUP_DIR})" >> ~/.tcshrc
source ~/.tcshrc
